import { FontSizeConfig, LetterSpacingConfig } from '@/components/molecules/TextEditor/types';

export const DEFAULT_FONT_CONFIGS = [
  { value: 'arial', label: 'Arial' },
  { value: 'comic-sans', label: 'Comic Sans' },
  { value: 'courier-new', label: 'Courier New' },
  { value: 'georgia', label: 'Georgia' },
  { value: 'helvetica', label: 'Helvetica' },
  { value: 'lucida', label: 'Lucida' },
  { value: 'times-new-roman', label: 'Times New Roman' },
  { value: 'verdana', label: 'Verdana' },
  { value: 'roboto', label: 'Roboto' },
  { value: 'calibri', label: 'Calibri' },
  { value: 'impact', label: 'Impact' },
  { value: 'palatino', label: 'Palatino' },
  { value: 'tahoma', label: 'Tahoma' },
  { value: 'garamond', label: 'Garamond' },
  { value: 'bookman', label: 'Bookman' },
  { value: 'cursive', label: 'Cursive' },
  { value: 'fantasy', label: 'Fantasy' },
  { value: 'monospace', label: 'Monospace' },
  { value: 'serif', label: 'Serif' },
  { value: 'sans-serif', label: 'Sans-serif' },
];
export const DEFAULT_FONT_SIZE_CONFIGS: FontSizeConfig[] = [
  { value: '14px', label: '14' },
  { value: '16px', label: '16' },
  { value: '18px', label: '18' },
  { value: '20px', label: '20' },
  { value: '24px', label: '24' },
  { value: '28px', label: '28' },
  { value: '30px', label: '30' },
  { value: '32px', label: '32' },
];
export const DEFAULT_LETTER_SPACING_CONFIGS: LetterSpacingConfig[] = [
  { value: '-10px', label: '-10' },
  { value: '-9px', label: '-9' },
  { value: '-8px', label: '-8' },
  { value: '-7px', label: '-7' },
  { value: '-6px', label: '-6' },
  { value: '-5px', label: '-5' },
  { value: '-4px', label: '-4' },
  { value: '-3px', label: '-3' },
  { value: '-2px', label: '-2' },
  { value: '-1px', label: '-1' },
  { value: '0px', label: '0' },
  { value: '1px', label: '1' },
  { value: '2px', label: '2' },
  { value: '3px', label: '3' },
  { value: '4px', label: '4' },
  { value: '5px', label: '5' },
  { value: '6px', label: '6' },
  { value: '7px', label: '7' },
  { value: '8px', label: '8' },
  { value: '9px', label: '9' },
  { value: '10px', label: '10' },
];

export const RQ_FORMATS = [
  'header',
  'font',
  'size',
  'bold',
  'italic',
  'underline',
  'align',
  'strike',
  'script',
  'blockquote',
  'background',
  'list',
  'bullet',
  'indent',
  'link',
  'color',
  'code-block',
];

